### ISSUE TITLE
Adapter is pulling data only once

### ISSUE THREAD

**Issue by Fl0Rue** [mcm1957/ioBroker.bayernluft-original#5]
Hello,
i startet to ise this adapter. When i start the adapter it pulls out the data once before the adapter runs on error and gets disabled.

Thats what the protocoll looks like:

bayernluft.0 | 2023-11-14 18:18:09.937 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
bayernluft.0 | 2023-11-14 18:18:09.936 | info | terminating
bayernluft.0 | 2023-11-14 18:18:09.856 | error | Parameter "ack" needs to be of type "boolean" but type "string" has been passed
bayernluft.0 | 2023-11-14 18:18:09.855 | error | Error: Parameter "ack" needs to be of type "boolean" but type "string" has been passed at Validator.assertBoolean (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/validator.js:195:19) at Bayernluft.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5403:35) at /opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2020:16 at new Promise (<anonymous>) at Bayernluft.setStateAsync (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/tools.js:2019:16) at Bayernluft.setObjectNotExistsAsyncEasy (/opt/iobroker/node_modules/iobroker.bayernluft/main.js:193:16) at async Bayernluft.checkDevices (/opt/iobroker/node_modules/iobroker.bayernluft/main.js:75:4) at async Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.bayernluft/main.js:43:4)
bayernluft.0 | 2023-11-14 18:18:09.852 | error | unhandled promise rejection: Parameter "ack" needs to be of type "boolean" but type "string" has been passed
bayernluft.0 | 2023-11-14 18:18:09.851 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
bayernluft.0 | 2023-11-14 18:17:11.893 | info | State value to set for "bayernluft.0.Bad.states.timer_active" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.839 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:11.838 | warn | Object bayernluft.0.Bad.states.timer_active is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.789 | info | State value to set for "bayernluft.0.Bad.states.cross_ventilation" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.735 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:11.734 | warn | Object bayernluft.0.Bad.states.cross_ventilation is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.685 | info | State value to set for "bayernluft.0.Bad.states.landlord_mode" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.631 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:11.630 | warn | Object bayernluft.0.Bad.states.landlord_mode is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.581 | info | State value to set for "bayernluft.0.Bad.states.defrosting" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.527 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:11.526 | warn | Object bayernluft.0.Bad.states.defrosting is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.477 | info | State value to set for "bayernluft.0.Bad.states.fixed_speed" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.420 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:11.419 | warn | Object bayernluft.0.Bad.states.fixed_speed is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.369 | info | State value to set for "bayernluft.0.Bad.states.Antifreeze" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.311 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:11.310 | warn | Object bayernluft.0.Bad.states.Antifreeze is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.257 | info | State value to set for "bayernluft.0.Bad.states.systemon" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.201 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:11.201 | warn | Object bayernluft.0.Bad.states.systemon is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.106 | info | State value to set for "bayernluft.0.Bad.parameter.humidity_transport" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:11.045 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:11.044 | warn | Object bayernluft.0.Bad.parameter.humidity_transport is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.993 | info | State value to set for "bayernluft.0.Bad.parameter.efficiency" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.937 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:10.936 | warn | Object bayernluft.0.Bad.parameter.efficiency is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.885 | info | State value to set for "bayernluft.0.Bad.parameter.abs_humidity_out" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.832 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:10.831 | warn | Object bayernluft.0.Bad.parameter.abs_humidity_out is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.782 | info | State value to set for "bayernluft.0.Bad.parameter.abs_humidity_in" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.730 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:10.727 | warn | Object bayernluft.0.Bad.parameter.abs_humidity_in is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.681 | info | State value to set for "bayernluft.0.Bad.parameter.rel_humidity_out" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.627 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:10.627 | warn | Object bayernluft.0.Bad.parameter.rel_humidity_out is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.580 | info | State value to set for "bayernluft.0.Bad.parameter.rel_humidity_in" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.524 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:10.522 | warn | Object bayernluft.0.Bad.parameter.rel_humidity_in is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.470 | info | State value to set for "bayernluft.0.Bad.parameter.temperature_fresh" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.416 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:10.415 | warn | Object bayernluft.0.Bad.parameter.temperature_fresh is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.365 | info | State value to set for "bayernluft.0.Bad.parameter.temperature_out" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.309 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:10.308 | warn | Object bayernluft.0.Bad.parameter.temperature_out is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.257 | info | State value to set for "bayernluft.0.Bad.parameter.temperature_in" has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:17:10.203 | warn | This object will not be created in future versions. Please report this to the developer.
bayernluft.0 | 2023-11-14 18:17:10.201 | warn | Object bayernluft.0.Bad.parameter.temperature_in is invalid: Default value has to be type "number" but received type "string"
bayernluft.0 | 2023-11-14 18:16:09.560 | info | starting. Version 1.2.2 (non-npm: Marco15453/ioBroker.bayernluft) in /opt/iobroker/node_modules/iobroker.bayernluft, node: v18.18.2, js-controller: 5.0.16
bayernluft.0 | 2023-11-14 18:16:05.070 | info | terminating
bayernluft.0 | 2023-11-14 18:16:04.706 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
bayernluft.0 | 2023-11-14 18:16:04.705 | info | terminating
bayernluft.0 | 2023-11-14 18:16:04.654 | error | An unexpected error has occred while trying to get response from device Bad.
bayernluft.0 | 2023-11-14 18:16:04.652 | error | An unexpected error has occred while trying to get response from device Bad.
bayernluft.0 | 2023-11-14 18:16:04.567 | info | Got terminate signal TERMINATE_YOURSELF
bayernluft.0 | 2023-11-14 18:15:04.396 | info | starting. Version 1.2.2 (non-npm: Marco15453/ioBroker.bayernluft) in /opt/iobroker/node_modules/iobroker.bayernluft, node: v18.18.2, js-controller: 5.0.16
bayernluft.0 | 2023-11-14 18:11:36.141 | info | terminating
bayernluft.0 | 2023-11-14 18:11:35.694 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
bayernluft.0 | 2023-11-14 18:11:35.692 | info | terminating
bayernluft.0 | 2023-11-14 18:11:35.637 | info | Got terminate signal TERMINATE_YOURSELF
bayernluft.0 | 2023-11-14 18:11:35.613 | error | No devices has been set, disabling adapter!
bayernluft.0 | 2023-11-14 18:11:35.531 | info | starting. Version 1.2.2 (non-npm: Marco15453/ioBroker.bayernluft) in /opt/iobroker/node_modules/iobroker.bayernluft, node: v18.18.2, js-controller: 5.0.16

What can i do to make it work?

**Comment by mcm1957** [comment]
This adapter is no longer maintained:
https://github.com/Marco15453/ioBroker.bayernluft/issues/6#issuecomment-2044612952
